### ISSUE TITLE
Simplify minimal-dependency install with pip

### ISSUE THREAD

**Issue by jtniehof** [spacepy/spacepy#737]
Some people have commented on the "heavy" dependencies for SpacePy; in some constrained environments scipy can be relatively big. We only really hard-require numpy and [document pretty heavily](https://spacepy.github.io/dependencies.html) what functionality is lost without a given dependency. However, `pip install` gets almost all the dependencies, by popular demand. (We don't install AstroPy, since we only use it to put data in/out of AstroPy...if you need it, you've got it.)

People can use `--no-deps` and manage manually, of course, but this is hard to do in a `requirements.txt`. So it would be nice if we could `pip install spacepy[minimal]` or something to only install numpy. It appears this is [not possible](https://stackoverflow.com/questions/60842775/how-to-package-a-python-module-with-extras-as-default)--pip "extras" are truly extra.

We could do something like default to numpy only and then use `pip install spacepy[full]`, but I think the default should be to get a reasonable set of dependencies.

I was thinking of starting to treat scipy, matplotlib, h5py as full-required but based on what I'm hearing, some people do like having the lighter dependency set. We just need an easy way of getting it to them.

**Comment by jtniehof** [comment]
Related: since we use astropy and pandas in the tests but don't install by default, it would be good to have a `[testing]` to install those.

**Comment by roballsopp** [comment]
Since the modules affected by each dependency are already so well documented, I'll cast a vote for something along these lines in the pyproject.toml so that we can pick and choose what modules we want to use:
```toml
[project]
...
dependencies = [
  "numpy>=1.15.1",
  "python_dateutil>=2.5",
]
[project.optional-dependencies]
plot = ["matplotlib>=3.1"]
sci = ["scipy>=1.0"]
h5py = ["h5py>=2.10"]
full = ["matplotlib>=3.1","scipy>=1.0","h5py>=2.10"]
```
Then, if I don't plan to use the plot or datamodel package, my requirements file could be:
```
spacepy[sci]~=0.7.0
```
